name: device_preview_demo
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: any

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/Lufga-Black.otf
          weight: 800
        - asset: assets/fonts/Lufga-Bold.otf
          weight: 700
        - asset: assets/fonts/Lufga-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Lufga-Medium.otf
          weight: 500
        - asset: assets/fonts/Lufga-Regular.otf
          weight: 400
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
